### ISSUE TITLE
Gérer le multi-server

### ISSUE THREAD

**Issue by Yanisiman** [GabRayz/Phoenix-Bot#31]
- [ ] 2 serveurs meme musiques quand j'éteins l'une ça stop les 2 je relance avec nouvelle musique sur l'un des 2 serv ça met l'ancienne musique et si je skip met ensuite la bonne

- [ ] 2 serveurs musiques différentes je skip sur l'un des serveurs ça skip les 2 donc plus aucune musique dans la queue

**Comment by GabRayz** [comment]
A été corrigé avec #21
